"""
Django settings for atlantis project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# env
load_dotenv(BASE_DIR / '.env')

HCA_CLIENT_ID = os.environ.get("HCA_CLIENT_ID")
HCA_CLIENT_SECRET = os.environ.get("HCA_CLIENT_SECRET")
HCA_CALLBACK_URI = os.environ.get("HCA_CALLBACK_URI")

# Fernet key (url-safe base64-encoded 32 bytes) used to encrypt the HCA OAuth
# tokens that shipping addresses are fetched with at rest. Addresses themselves
# are never stored. Generate with: Fernet.generate_key().decode()
ADDRESS_ENCRYPTION_KEY = os.environ.get("ADDRESS_ENCRYPTION_KEY")

# fucking cloudflare bs
AWS_ACCESS_KEY_ID = os.environ["R2_ACCESS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["R2_ACCESS_KEY"]
AWS_STORAGE_BUCKET_NAME = os.environ["R2_BUCKET_NAME"]
AWS_S3_ENDPOINT_URL = os.environ["R2_ENDPOINT"]
AWS_S3_REGION_NAME = "auto"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_DEFAULT_ACL = None
AWS_S3_FILE_OVERWRITE = True

SLACK_TOKEN = os.environ["SLACK_TOKEN"]

LOOKOUT_TOKEN = os.environ["LOOKOUT_TOKEN"]
LOOKOUT_BASE_URL = os.environ.get("LOOKOUT_BASE_URL", "https://lookout.hackclub.com")
LOOKOUT_APP_NAME = os.environ.get("LOOKOUT_APP_NAME", "Atlantis")

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "atlantis.storage.NonStrictManifestStaticFilesStorage",
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"
ALLOW_JOURNALING = os.environ.get("ALLOW_JOURNALING", "False") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'atlantis_site',
    'storages'
]

try:
    import django_extensions  # noqa: F401
    INSTALLED_APPS.append('django_extensions')
except ImportError:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'atlantis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'root'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'atlantis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["POSTGRES_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.environ["POSTGRES_HOST"],
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Cache
# https://docs.djangoproject.com/en/6.0/topics/cache/
#
# Backed by a Postgres table (created by migration 0041) so cache state — most
# importantly the rate-limit windows in views.helpers.rate_limit — is shared
# across all gunicorn workers rather than living per-process. A high MAX_ENTRIES
# keeps active rate-limit windows from being culled early under load.

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "atlantis_cache",
        "OPTIONS": {
            "MAX_ENTRIES": 10000,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_TRUSTED_ORIGINS = [
    'https://atlantis.hackclub.com',
    'https://*.atlantis.hackclub.com',
    'https://localhost:8000'
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

SECURE_SSL = os.environ.get("SECURE_SSL", "False" if DEBUG else "True") == "True"

SECURE_SSL_REDIRECT = SECURE_SSL
SESSION_COOKIE_SECURE = SECURE_SSL
CSRF_COOKIE_SECURE = SECURE_SSL
if SECURE_SSL:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# CVE-2026-6873: older Django derived a signed cookie's salt by concatenating
# the cookie name and salt, so distinct (name, salt) pairs could collide and a
# cookie could be accepted in a context it wasn't signed for. Django accepts
# legacy-salted cookies until 7.0 by default; we sign no cookies ourselves, so
# there is nothing to migrate and the fallback can be off now.
SIGNED_COOKIE_LEGACY_SALT_FALLBACK = False

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

JAZZMIN_SETTINGS = {
    "site_title": "Atlantis Supadmin",
    "site_header": "Atlantis Supadmin",
    "site_brand": "Atlantis",
    "site_icon": "atlantis_site/assets/img/favicon.png?v=2",
    "welcome_sign": "log in you naughty naughty",
    "copyright": "Hack Club",
    "search_model": "auth.User",
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-info",
    "navbar": "navbar-dark navbar-teal",
    "no_customize": False,
    "sidebar_themes": True,
    "theme": "solar",
    "default_theme_mode": "auto",
    "sidebar": "sidebar-dark-teal", 
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_sidebar": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"