# Generated by Django 6.0.5 on 2026-06-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0004_alter_permissions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('W', 'Working on'), ('T1', 'Under T1 Review'), ('PQ', 'In print queue'), ('BP', 'Being printed'), ('T2', 'Under T2 Review'), ('T3', 'Under fraud review'), ('F', 'Finalized')], default='W', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='printablesUrl',
            field=models.CharField(max_length=150),
        ),
    ]
