# Generated by Django 6.0.5 on 2026-06-05 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0005_project_status_alter_project_printablesurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('W', 'Working on'), ('T1', 'Under T1 Review'), ('PQ', 'In print queue'), ('BP', 'Being printed'), ('T2', 'Under T2 Review'), ('T3', 'Under fraud review'), ('F', 'Finalized'), ('L', 'Locked')], default='W', max_length=2)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='layered_site.project')),
            ],
        ),
    ]
