# Generated by Django 6.0.5 on 2026-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0007_alter_permissions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.CharField(choices=[('T1', 'Under T1 Review'), ('PQ', 'In print queue'), ('BP', 'Being printed'), ('T2', 'Under T2 Review'), ('T3', 'Under fraud review'), ('F', 'Finalized')], default='T1', max_length=2),
        ),
    ]
