# Generated by Django 6.0.5 on 2026-06-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0013_profile_layers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Fulfilled'), ('D', 'Denied'), ('R', 'Refunded')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='user_notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
