# Generated by Django 6.0.5 on 2026-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0029_alter_print_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t3',
            name='airtable_hours',
        ),
        migrations.RemoveField(
            model_name='t3',
            name='payout_hours',
        ),
        migrations.AddField(
            model_name='t3',
            name='airtable_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t3',
            name='payout_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
