# Generated by Django 6.0.5 on 2026-07-08 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0032_project_editor_model_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='imageUrl',
            field=models.URLField(default='https://example.com', max_length=2048),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfiller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_fulfilled', to=settings.AUTH_USER_MODEL),
        ),
    ]
