# Generated by Django 6.0.5 on 2026-06-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0003_item_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('t1_review', 'T1 Project Review'), ('t2_review', 'T2 Project Review'), ('t3_review', 'T3/Fraud Project Review'), ('printer', 'Project Printer'), ('fulfillment', 'Fulfill shop orders')]},
        ),
    ]
