# Generated by Django 6.0.5 on 2026-06-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0006_remove_project_status_ship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('t1_review', 'T1 Project Review'), ('t2_review', 'T2 Project Review'), ('t3_review', 'T3/Fraud Project Review'), ('printer', 'Project Printer'), ('fulfillment', 'Fulfill shop orders'), ('organizer', 'Access to everything')]},
        ),
    ]
