# Generated by Django 6.0.5 on 2026-06-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='layers',
            field=models.IntegerField(default=0),
        ),
    ]
