# Generated by Django 6.0.5 on 2026-06-13 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0015_print_t1_t2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imageUrl',
            field=models.CharField(default='https://example.com', max_length=2048),
        ),
        migrations.AlterField(
            model_name='print',
            name='image_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=2000)),
                ('image_url', models.CharField(max_length=2048)),
                ('model_url', models.CharField(max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='atlantis_site.project')),
            ],
        ),
    ]
