# Generated by Django 6.0.5 on 2026-06-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0020_rename_internal_comments_t3_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
