# Generated by Django 6.0.5 on 2026-06-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0021_print_finished_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='decision',
            field=models.CharField(choices=[('T1', 'Returned to T1 Review'), ('U', 'Unclaimed, back in printing queue'), ('A', 'Approve')], default='A', max_length=2),
        ),
    ]
