# Generated by Django 6.0.5 on 2026-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0022_alter_print_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='printablesUrl',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
