# Generated by Django 6.0.5 on 2026-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0023_alter_project_printablesurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slack_pfp_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='slack_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
