# Generated by Django 6.0.5 on 2026-06-22 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0024_profile_slack_pfp_url_profile_slack_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
