# Generated by Django 6.0.5 on 2026-06-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0025_journal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='atlantis_site.ship'),
        ),
        migrations.AddField(
            model_name='ship',
            name='submitted_time',
            field=models.IntegerField(default=0),
        ),
    ]
