# Generated by Django 6.0.5 on 2026-06-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0026_journal_ship_ship_submitted_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='submitted_time',
        ),
    ]
