# Generated by Django 6.0.5 on 2026-06-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0028_order_fulfiller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='decision',
            field=models.CharField(choices=[('T1', 'Returned to T1 Review'), ('U', 'Unclaimed, back in printing queue'), ('P', 'Being printed'), ('A', 'Approve')], default='P', max_length=2),
        ),
    ]
