# Generated by Django 6.0.5 on 2026-07-21 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0035_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
