# Generated by Django 6.0.5 on 2026-07-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0037_item_is_print_reward_profile_print_reward_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=-1, help_text='Units available to order. -1 means unlimited stock.'),
        ),
    ]
