# Generated by Django 6.0.5 on 2026-07-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0038_item_stock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='atlantis_si_created_718cfc_idx',
            old_name='layered_sit_created_b9e83d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='atlantis_si_action_92933b_idx',
            old_name='layered_sit_action_8078a8_idx',
        ),
    ]
