# Generated by Django 6.0.5 on 2026-07-23 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0039_rename_layered_sit_created_b9e83d_idx_atlantis_si_created_718cfc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('compiling', 'Compiling'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('tracked_seconds', models.IntegerField(default=0)),
                ('total_active_seconds', models.IntegerField(default=0)),
                ('screenshot_count', models.IntegerField(default=0)),
                ('heartbeats_forwarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelapses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelapses', to='atlantis_site.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
