# Generated by Django 6.0.5 on 2026-07-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0041_create_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
