# Generated by Django 6.0.5 on 2026-07-30 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0042_profile_encrypted_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='lookoutsession',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelapses', to='atlantis_site.journal'),
        ),
    ]
