# Generated by Django 6.0.5 on 2026-08-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0043_remove_journal_time_spent_lookoutsession_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='encrypted_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='encrypted_hca_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
