# Generated by Django 6.0.5 on 2026-08-04 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0044_remove_profile_encrypted_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_comments', to=settings.AUTH_USER_MODEL)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_comments', to='atlantis_site.ship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
