# Generated by Django 6.0.5 on 2026-08-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0045_internalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
