# Generated by Django 6.0.8 on 2026-08-23 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0048_remove_printing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('t1_review', 'T1 Project Review'), ('t2_review', 'T2 Project Review'), ('t3_review', 'T3/Fraud Project Review'), ('timelapse_review', 'Timelapse Review (internal)'), ('fulfillment', 'Fulfill shop orders'), ('organizer', 'Access to everything')], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.CreateModel(
            name='TimelapseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('internal_notes', models.CharField(blank=True, max_length=1000)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timelapse_review', to='atlantis_site.journal')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timelapse_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelapseRemoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.PositiveIntegerField()),
                ('end_seconds', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removals', to='atlantis_site.lookoutsession')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removals', to='atlantis_site.timelapsereview')),
            ],
            options={
                'ordering': ['session_id', 'start_seconds'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_seconds__gt', models.F('start_seconds'))), name='timelapse_removal_end_after_start'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='timelapse_removal_reason_required')],
            },
        ),
    ]
