# Generated by Django 6.0.8 on 2026-08-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0049_timelapse_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Not yet submitted'), ('sending', 'Submission in flight'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('record_id', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airtable_submission', to='atlantis_site.ship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
