# Generated by Django 6.0.8 on 2026-08-23 21:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0050_airtable_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='t2',
            name='payout_multiplier',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('3.0'))]),
        ),
    ]
