# Generated by Django 6.0.8 on 2026-08-26 00:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def carry_multipliers_to_t3(apps, schema_editor):
    """Give each existing T3 the multiplier that was in force when it ran.

    t3_decision used to read the ship's latest T2 at the moment it paid out,
    so the T2 a review was scored against is the newest one on that ship from
    before the review — anything later belongs to a return trip through T2.
    """
    T2 = apps.get_model("atlantis_site", "T2")
    T3 = apps.get_model("atlantis_site", "T3")

    for t3 in T3.objects.all().iterator():
        t2 = (
            T2.objects.filter(ship_id=t3.ship_id, reviewed_at__lte=t3.reviewed_at)
            .order_by("-id")
            .first()
        )
        if t2 and t2.payout_multiplier != t3.payout_multiplier:
            t3.payout_multiplier = t2.payout_multiplier
            t3.save(update_fields=["payout_multiplier"])


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0052_shopcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3',
            name='payout_multiplier',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('3.0'))]),
        ),
        # Copy before the drop, so a finished review still records the
        # multiplier its payout was actually computed with.
        migrations.RunPython(carry_multipliers_to_t3, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='t2',
            name='payout_multiplier',
        ),
    ]
