# Generated by Django 6.0.8 on 2026-08-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0053_move_payout_multiplier_to_t3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelapsereview',
            name='internal_notes',
            field=models.CharField(max_length=1000),
        ),
    ]
