# Generated by Django 6.0.8 on 2026-08-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0054_alter_timelapsereview_internal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1',
            name='feedback',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='t1',
            name='internal_notes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='t2',
            name='feedback',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='t2',
            name='justification',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='timelapseremoval',
            name='reason',
            field=models.CharField(max_length=1000),
        ),
    ]
