# Generated by Django 6.0.8 on 2026-08-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0055_alter_t1_feedback_alter_t1_internal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ysws_eligible',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
