"""Inactivity detection on Lookout footage, and per-Lookout descriptions.

The four columns on LookoutSession are what activity.py writes: how much
of a compiled video shows no change, and where. TimelapseAnnotation is the
sentence a reviewer writes about each piece of footage they watched, which
is now what carries the account of a pass — so TimelapseReview's own notes
become optional, a place for anything spanning the whole project.
"""

# Generated by Django 6.0.8 on 2026-08-29 19:38

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0056_profile_ysws_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookoutsession',
            name='activity_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lookoutsession',
            name='inactive_frame_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lookoutsession',
            name='inactive_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lookoutsession',
            name='inactive_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='timelapsereview',
            name='internal_notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='TimelapseAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='atlantis_site.timelapsereview')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='atlantis_site.lookoutsession')),
            ],
            options={
                'ordering': ['session_id'],
                'constraints': [models.UniqueConstraint(fields=('review', 'session'), name='timelapse_annotation_one_per_session')],
            },
        ),
    ]
