"""The measured length of a compiled Lookout video.

Until now the review page worked out how long a video ran by dividing the
session's credited time by sixty, which is short of the truth by every
screenshot Lookout took but never credited — the tail of the footage fell off
the timeline and out of reach of a cut. The activity check reads the real
length off the file now, and this is where it goes; null until something has
looked at that session's video.
"""

# Generated by Django 6.0.8 on 2026-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0057_timelapse_activity_and_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookoutsession',
            name='measured_video_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
