"""Lookout out, Lapse in.

Written by hand rather than autogenerated, and the reason is the first
operation. Left to itself Django reads this as "delete LookoutSession, create
Timelapse", because almost every column changed — and dropping that table takes
every TimelapseRemoval and TimelapseAnnotation with it on the cascade. Those
rows are the audit trail for hours that were already cut from real people's
ships, and HQ has the justification text that cites them. So the table is
renamed and altered in place, and the history survives.

What the old rows keep and what they lose is worth being clear about. Their
`session_id` was a Lookout session UUID and becomes `lapse_id`, which keeps them
unique and keeps the removals pointing at the right footage. `playback_url` is
backfilled from Lookout's media URL, which still serves those videos — it is
the same URL Lapse's own API hands out for footage it inherited. What a legacy
row does *not* have is a real Lapse id, so `watch_url` on one points at a page
that will not resolve. Everything written from here on gets both.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Where Lookout's compiled videos are still served from. Hardcoded rather than
# read off settings: that setting is gone as of this change, and a migration
# has to keep working without it.
LOOKOUT_MEDIA_BASE = "https://lookout.hackclub.com/api/media"


def backfill_media(apps, schema_editor):
    """Point the rows carried over from Lookout at their videos.

    `recorded_at` is filled from `created_at` for them. Under Lookout a row was
    created when the recording started, so the two really were the same moment;
    under Lapse they are not, which is why the column exists.
    """
    Timelapse = apps.get_model("atlantis_site", "Timelapse")
    for timelapse in Timelapse.objects.filter(playback_url="").iterator():
        timelapse.playback_url = f"{LOOKOUT_MEDIA_BASE}/{timelapse.lapse_id}/video.mp4"
        timelapse.thumbnail_url = f"{LOOKOUT_MEDIA_BASE}/{timelapse.lapse_id}/thumbnail.jpg"
        timelapse.recorded_at = timelapse.created_at
        timelapse.save(update_fields=["playback_url", "thumbnail_url", "recorded_at"])


def unbackfill_media(apps, schema_editor):
    """No-op. Going back drops these columns anyway."""


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("atlantis_site", "0058_lookoutsession_measured_video_seconds"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LookoutSession",
            new_name="Timelapse",
        ),
        migrations.RenameField(
            model_name="timelapse",
            old_name="session_id",
            new_name="lapse_id",
        ),
        migrations.AlterModelOptions(
            name="timelapse",
            options={"ordering": ["-recorded_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="timelapse",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="playback_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="thumbnail_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_media, unbackfill_media),
        # Everything below this line was Lookout's alone: a session had a
        # lifecycle here because we drove it. A Lapse timelapse arrives finished.
        migrations.RemoveField(model_name="timelapse", name="token"),
        migrations.RemoveField(model_name="timelapse", name="status"),
        migrations.RemoveField(model_name="timelapse", name="screenshot_count"),
        migrations.RemoveField(model_name="timelapse", name="total_active_seconds"),
        migrations.RemoveField(model_name="timelapse", name="heartbeats_forwarded"),
        migrations.CreateModel(
            name="LapseAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lapse_user_id", models.CharField(blank=True, default="", max_length=64)),
                ("handle", models.CharField(blank=True, default="", max_length=64)),
                ("display_name", models.CharField(blank=True, default="", max_length=64)),
                ("profile_picture_url", models.CharField(blank=True, default="", max_length=300)),
                ("encrypted_token", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.CharField(blank=True, default="", max_length=200)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="lapse_account",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]
