"""Lapse arrives; Lookout stays on as legacy.

Written by hand rather than autogenerated, and the reason is the first
operation. Left to itself Django reads this as "delete LookoutSession, create
Timelapse" — and dropping that table takes every TimelapseRemoval and
TimelapseAnnotation with it on the cascade. Those rows are the audit trail for
hours that were already cut from real people's ships, and HQ has the
justification text that cites them. So the table is renamed and altered in
place, and the history survives.

Nothing is dropped here. Every Lookout column stays exactly where it was,
because Lookout keeps working: sessions already in flight still record, footage
already recorded still attaches, and the review desks still read all of it. The
change is that rows now say which recorder they came from, and that a Lapse row
can sit next to a Lookout one in the same table.

What existing rows become: `source` is "lookout" for all of them, which is what
they are. Their `session_id` and `token` are untouched. `lapse_id`, `name`,
`playback_url` and `recorded_at` are empty on them, and every one of those is
read through a property that already knows to fall back for a Lookout row.

`session_id` and `token` lose `unique=True` in favour of unique constraints
that only apply where the column is non-empty. A Lapse row has neither, and a
plain unique index would have allowed exactly one such row to exist.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_recorded_at(apps, schema_editor):
    """Give the carried-over rows the recorded time the new ordering needs.

    Under Lookout a row was created when recording started, so `created_at`
    really is when that footage is from. It matters because the table is now
    ordered on `recorded_at` descending, and Postgres sorts nulls *first* — so
    leaving these empty would file every piece of legacy footage ahead of
    everything recorded since.
    """
    Timelapse = apps.get_model("atlantis_site", "Timelapse")
    Timelapse.objects.filter(recorded_at__isnull=True).update(
        recorded_at=models.F("created_at")
    )


def unbackfill_recorded_at(apps, schema_editor):
    """No-op. Going back drops the column anyway."""


def fill_missing_session_ids(apps, schema_editor):
    """Make sure every carried-over row satisfies the new check constraint.

    A Lookout row must have a session id, and in practice every one does —
    start_timelapse refuses to write a row without one, and the old unique
    index allowed at most a single blank anyway. This exists so that if one
    ever did slip through, the deploy adding the constraint doesn't fail on it
    at the worst possible moment.
    """
    Timelapse = apps.get_model("atlantis_site", "Timelapse")
    for pk in Timelapse.objects.filter(session_id="").values_list("pk", flat=True):
        Timelapse.objects.filter(pk=pk).update(session_id=f"unknown-session-{pk}")


def noop(apps, schema_editor):
    """Forward direction of the rollback repair: nothing to do."""


def repair_for_rollback(apps, schema_editor):
    """Give the Lapse rows enough Lookout shape that a rollback boots.

    Read this before relying on a rollback. Reversing this migration takes the
    table back to "every row is a Lookout session", and a Lapse row is not one:
    it has no session id and no token, and the columns it would need them in
    are about to become UNIQUE NOT NULL again.

    What this does is make the reverse legal and leave the old code something
    coherent to run on. The hours survive — `tracked_seconds` is untouched, so
    nobody loses time they earned, and the journals still add up. What breaks
    is the footage behind them: the old code builds a video URL out of the
    session id, and these placeholders point at nothing on Lookout. The
    placeholders are deliberately not plausible session ids, so nothing can
    talk to Lookout with one and think it worked.

    If the real footage matters after a rollback — and for anything still
    awaiting timelapse review it does — roll forward again rather than trying
    to repair by hand. The Lapse ids are preserved in `lapse_id` right up until
    the column is dropped, which is the last operation to reverse.
    """
    Timelapse = apps.get_model("atlantis_site", "Timelapse")
    for row in Timelapse.objects.filter(source="lapse").iterator():
        Timelapse.objects.filter(pk=row.pk).update(
            session_id=f"rolled-back-{row.pk}",
            token=f"rolled-back-{row.pk}",
            # These arrived finished, so the old code should treat them as
            # finished; their hours are already attached to journals.
            status="complete",
            # One shot per recorded minute, the same figure the old code fell
            # back to when a count had never synced.
            screenshot_count=(row.tracked_seconds or 0) // 60,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("atlantis_site", "0058_lookoutsession_measured_video_seconds"),
        # Not decorative. RenameModel makes Django rename the model's content
        # type too, through an operation it injects into the plan itself. That
        # operation reads ContentType out of the *historical* app state, and
        # without this dependency the state it gets is the one from before
        # contenttypes.0002 dropped `name` — so reversing this migration
        # queries a column the database has not had for a decade and dies with
        # "column django_content_type.name does not exist". Pinning the
        # dependency puts the real ContentType in that state, which is what
        # makes the rollback work.
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LookoutSession",
            new_name="Timelapse",
        ),
        migrations.AlterModelOptions(
            name="timelapse",
            options={"ordering": ["-recorded_at", "-created_at"]},
        ),
        # Added as "lookout", which backfills every existing row correctly,
        # then re-defaulted to "lapse" to match the model: new rows come from
        # the picker unless the legacy recorder says otherwise.
        migrations.AddField(
            model_name="timelapse",
            name="source",
            field=models.CharField(
                choices=[("lapse", "Lapse"), ("lookout", "Lookout (legacy)")],
                default="lookout",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="timelapse",
            name="source",
            field=models.CharField(
                choices=[("lapse", "Lapse"), ("lookout", "Lookout (legacy)")],
                default="lapse",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="lapse_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="playback_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="lapse_thumbnail_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Reversed, this runs after repair_for_rollback below has given every
        # Lapse row a placeholder, which is what lets the columns go back to
        # UNIQUE NOT NULL without tripping over them.
        migrations.AlterField(
            model_name="timelapse",
            name="session_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="timelapse",
            name="token",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.RunPython(backfill_recorded_at, unbackfill_recorded_at),
        migrations.RunPython(fill_missing_session_ids, migrations.RunPython.noop),
        migrations.RunPython(noop, repair_for_rollback),
        migrations.AddConstraint(
            model_name="timelapse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lapse_id", ""), _negated=True),
                fields=("lapse_id",),
                name="timelapse_lapse_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="timelapse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_id", ""), _negated=True),
                fields=("session_id",),
                name="timelapse_session_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="timelapse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("token", ""), _negated=True),
                fields=("token",),
                name="timelapse_token_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="timelapse",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("source", "lapse"))
                    & models.Q(("lapse_id", ""), _negated=True)
                ) | (
                    models.Q(("source", "lookout"))
                    & models.Q(("session_id", ""), _negated=True)
                ),
                name="timelapse_source_has_id",
            ),
        ),
        migrations.CreateModel(
            name="LapseAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lapse_user_id", models.CharField(blank=True, default="", max_length=64)),
                ("handle", models.CharField(blank=True, default="", max_length=64)),
                ("display_name", models.CharField(blank=True, default="", max_length=64)),
                ("profile_picture_url", models.CharField(blank=True, default="", max_length=300)),
                ("encrypted_token", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.CharField(blank=True, default="", max_length=200)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="lapse_account",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]
