"""Lookout out, Lapse in.

Written by hand rather than autogenerated, and the reason is the first
operation. Left to itself Django reads this as "delete LookoutSession, create
Timelapse", because almost every column changed — and dropping that table takes
every TimelapseRemoval and TimelapseAnnotation with it on the cascade. Those
rows are the audit trail for hours that were already cut from real people's
ships, and HQ has the justification text that cites them. So the table is
renamed and altered in place, and the history survives.

What the old rows keep and what they lose is worth being clear about. Their
`session_id` was a Lookout session UUID and becomes `lapse_id`, which keeps them
unique and keeps the removals pointing at the right footage. `playback_url` is
backfilled from Lookout's media URL, which still serves those videos — it is
the same URL Lapse's own API hands out for footage it inherited. What a legacy
row does *not* have is a real Lapse id, so `watch_url` on one points at a page
that will not resolve. Everything written from here on gets both.
"""

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Where Lookout's compiled videos are still served from. Hardcoded rather than
# read off settings: that setting is gone as of this change, and a migration
# has to keep working without it.
LOOKOUT_MEDIA_BASE = "https://lookout.hackclub.com/api/media"


def backfill_media(apps, schema_editor):
    """Point the rows carried over from Lookout at their videos.

    `recorded_at` is filled from `created_at` for them. Under Lookout a row was
    created when the recording started, so the two really were the same moment;
    under Lapse they are not, which is why the column exists.
    """
    Timelapse = apps.get_model("atlantis_site", "Timelapse")
    for timelapse in Timelapse.objects.filter(playback_url="").iterator():
        timelapse.playback_url = f"{LOOKOUT_MEDIA_BASE}/{timelapse.lapse_id}/video.mp4"
        timelapse.thumbnail_url = f"{LOOKOUT_MEDIA_BASE}/{timelapse.lapse_id}/thumbnail.jpg"
        timelapse.recorded_at = timelapse.created_at
        timelapse.save(update_fields=["playback_url", "thumbnail_url", "recorded_at"])


def unbackfill_media(apps, schema_editor):
    """No-op. Going back drops these columns anyway."""


def noop(apps, schema_editor):
    """Forward direction of the rollback repair: nothing to do."""


def repair_lookout_state(apps, schema_editor):
    """Put enough back in the Lookout-only columns that a rollback boots.

    Read this before relying on a rollback. The forward migration *drops*
    `token`, `status` and `screenshot_count`; that data is gone from the
    database and nothing here can bring it back. What this does is make the
    reverse possible at all and leave the old code something coherent to run
    on. If the real values matter, restore a backup taken before the deploy
    instead — that is the only honest way to get them.

    What each column becomes:

    `token` — a fresh unique placeholder. It is what makes the reverse legal
    (the column is UNIQUE NOT NULL, and a table of empty strings cannot satisfy
    that), and it is deliberately not a plausible Lookout token: nothing should
    be able to talk to Lookout with it and think it worked. Starting a *new*
    recording still works, because that mints its own.

    `status` — a recording that reached a journal was complete, so it is marked
    complete and the hours on it keep working. One that never did cannot be
    resumed with a token we no longer have, so it is marked failed rather than
    left to look resumable and fail at the first click.

    `screenshot_count` — one shot per recorded minute, which is the same figure
    the old code fell back to when a count had never synced.
    """
    Timelapse = apps.get_model("atlantis_site", "Timelapse")
    for row in Timelapse.objects.all().iterator():
        Timelapse.objects.filter(pk=row.pk).update(
            token=f"rolled-back-{uuid.uuid4().hex}",
            status="complete" if row.journal_id else "failed",
            screenshot_count=(row.tracked_seconds or 0) // 60,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("atlantis_site", "0058_lookoutsession_measured_video_seconds"),
        # Not decorative. RenameModel makes Django rename the model's content
        # type too, through an operation it injects into the plan itself. That
        # operation reads ContentType out of the *historical* app state, and
        # without this dependency the state it gets is the one from before
        # contenttypes.0002 dropped `name` — so reversing this migration
        # queries a column the database has not had for a decade and dies with
        # "column django_content_type.name does not exist". Pinning the
        # dependency puts the real ContentType in that state, which is what
        # makes the rollback work.
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LookoutSession",
            new_name="Timelapse",
        ),
        migrations.RenameField(
            model_name="timelapse",
            old_name="session_id",
            new_name="lapse_id",
        ),
        migrations.AlterModelOptions(
            name="timelapse",
            options={"ordering": ["-recorded_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="timelapse",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="playback_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="thumbnail_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="timelapse",
            name="recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_media, unbackfill_media),
        # Everything below this line was Lookout's alone: a session had a
        # lifecycle here because we drove it. A Lapse timelapse arrives finished.
        #
        # The next three operations exist as three, rather than one RemoveField,
        # so that this migration can be rolled back on a database with rows in
        # it. Reversed, they run bottom to top: the column comes back nullable,
        # the repair fills it with unique values, and only then is it tightened
        # to UNIQUE NOT NULL. Dropping `token` in one step would reverse into
        # "column token contains null values" on any table that is not empty.
        migrations.AlterField(
            model_name="timelapse",
            name="token",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
        migrations.RunPython(noop, repair_lookout_state),
        migrations.RemoveField(model_name="timelapse", name="token"),
        migrations.RemoveField(model_name="timelapse", name="status"),
        migrations.RemoveField(model_name="timelapse", name="screenshot_count"),
        migrations.RemoveField(model_name="timelapse", name="total_active_seconds"),
        migrations.RemoveField(model_name="timelapse", name="heartbeats_forwarded"),
        migrations.CreateModel(
            name="LapseAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lapse_user_id", models.CharField(blank=True, default="", max_length=64)),
                ("handle", models.CharField(blank=True, default="", max_length=64)),
                ("display_name", models.CharField(blank=True, default="", max_length=64)),
                ("profile_picture_url", models.CharField(blank=True, default="", max_length=300)),
                ("encrypted_token", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.CharField(blank=True, default="", max_length=200)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="lapse_account",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]
