"""More room in a shop item's description.

A hundred characters was enough for a name and a unit and nothing else, so
the details that actually decide an order — filament weight, colour, what the
kit does and does not include — had to be left out. Five hundred now.
"""

# Generated by Django 6.0.8 on 2026-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0059_lapse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
