# Generated by Django 6.0.8 on 2026-09-19 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0062_profile_last_seen_activeday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MihiActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_on', models.DateField()),
                ('activations_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mihi_activations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activated_on'],
                'constraints': [models.UniqueConstraint(fields=('user', 'activated_on'), name='mihi_once_per_user_per_day')],
            },
        ),
    ]
