# Generated by Django 6.0.8 on 2026-09-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0067_reviewer_lead_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='t1',
            name='changes_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('C', 'Changes requested'), ('T1', 'Under T1 Review'), ('T2', 'Under T2 Review'), ('T3', 'Under fraud review'), ('F', 'Finalized')], default='T1', max_length=2),
        ),
    ]
