# Generated by Django 6.0.8 on 2026-10-02 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0071_profile_banned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='flag_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('C', 'Changes requested'), ('T1', 'Under T1 Review'), ('T2', 'Under T2 Review'), ('T3', 'Under final review'), ('F', 'Finalized')], default='T1', max_length=2),
        ),
        migrations.AlterField(
            model_name='t2',
            name='decision',
            field=models.CharField(choices=[('T1', 'Returned to T1 Review'), ('A', 'Approved'), ('C', 'Changes requested')], default='A', max_length=2),
        ),
    ]
