# Generated by Django 6.0.8 on 2026-10-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis_site', '0072_project_flag_t2_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='t3',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
